"""add kokoro to voiceprovider enum

Revision ID: 9867e4d709e3
Revises: a1b2c3d4e5f6
Create Date: 2026-07-12 06:13:21.038281+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9867e4d709e3'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE voiceprovider ADD VALUE IF NOT EXISTS 'kokoro'")

    op.alter_column('channel_automations', 'automation_status',
               existing_type=postgresql.ENUM('stopped', 'running', 'paused', name='automationstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channel_automations', 'cumulative_active_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channel_automations', 'long_video_interval_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channel_automations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channel_automations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'failed', 'complete', name='pipelinestatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_pipeline_runs_created_at', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_topic_id', table_name='pipeline_runs')
    op.drop_constraint('pipeline_runs_video_id_fkey', 'pipeline_runs', type_='foreignkey')
    op.drop_constraint('pipeline_runs_upload_id_fkey', 'pipeline_runs', type_='foreignkey')
    op.drop_constraint('pipeline_runs_topic_id_fkey', 'pipeline_runs', type_='foreignkey')
    op.drop_constraint('pipeline_runs_script_id_fkey', 'pipeline_runs', type_='foreignkey')
    op.drop_constraint('pipeline_runs_channel_id_fkey', 'pipeline_runs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_runs', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'pipeline_runs', 'scripts', ['script_id'], ['id'])
    op.create_foreign_key(None, 'pipeline_runs', 'uploads', ['upload_id'], ['id'])
    op.create_foreign_key(None, 'pipeline_runs', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'pipeline_runs', 'videos', ['video_id'], ['id'])
    op.alter_column('scripts', 'seo_gate_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('uploads', 'publish_status',
               existing_type=postgresql.ENUM('draft', 'approved', 'scheduled', 'rejected', name='publishstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('uploads', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('uploads', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_uploads_publish_status_scheduled_at', table_name='uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_uploads_publish_status_scheduled_at', 'uploads', ['publish_status', 'scheduled_at'], unique=False)
    op.alter_column('uploads', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('uploads', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('uploads', 'publish_status',
               existing_type=postgresql.ENUM('draft', 'approved', 'scheduled', 'rejected', name='publishstatus'),
               server_default=sa.text("'draft'::publishstatus"),
               existing_nullable=False)
    op.alter_column('scripts', 'seo_gate_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.create_foreign_key('pipeline_runs_channel_id_fkey', 'pipeline_runs', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pipeline_runs_script_id_fkey', 'pipeline_runs', 'scripts', ['script_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('pipeline_runs_topic_id_fkey', 'pipeline_runs', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pipeline_runs_upload_id_fkey', 'pipeline_runs', 'uploads', ['upload_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('pipeline_runs_video_id_fkey', 'pipeline_runs', 'videos', ['video_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_pipeline_runs_topic_id', 'pipeline_runs', ['topic_id'], unique=False)
    op.create_index('ix_pipeline_runs_status', 'pipeline_runs', ['status'], unique=False)
    op.create_index('ix_pipeline_runs_created_at', 'pipeline_runs', ['created_at'], unique=False)
    op.alter_column('pipeline_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'max_retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pipeline_runs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'failed', 'complete', name='pipelinestatus'),
               server_default=sa.text("'pending'::pipelinestatus"),
               existing_nullable=False)
    op.alter_column('channels', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('channels', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=False)
    op.alter_column('channel_automations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('channel_automations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('channel_automations', 'long_video_interval_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2'),
               existing_nullable=False)
    op.alter_column('channel_automations', 'cumulative_active_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('channel_automations', 'automation_status',
               existing_type=postgresql.ENUM('stopped', 'running', 'paused', name='automationstatus'),
               server_default=sa.text("'stopped'::automationstatus"),
               existing_nullable=False)
    # ### end Alembic commands ###
