"""thumbnail uses script

Revision ID: 45d7c2c90c5a
Revises: 0001_initial
Create Date: 2026-06-28 18:06:40.918210+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45d7c2c90c5a'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_logs', 'level',
               existing_type=postgresql.ENUM('debug', 'info', 'warning', 'error', 'critical', name='agentloglevel'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_agent_logs_agent_name', table_name='agent_logs')
    op.drop_index('ix_agent_logs_created_at', table_name='agent_logs')
    op.drop_index('ix_agent_logs_level', table_name='agent_logs')
    op.alter_column('analytics', 'snapshot_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'views',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'likes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'comments',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'shares',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'watch_time_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'average_view_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'average_view_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'ctr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'impressions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'subscribers_gained',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'subscribers_lost',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_analytics_snapshot_date', table_name='analytics')
    op.drop_index('ix_analytics_upload_id', table_name='analytics')
    op.drop_constraint('analytics_upload_id_fkey', 'analytics', type_='foreignkey')
    op.create_foreign_key(None, 'analytics', 'uploads', ['upload_id'], ['id'])
    op.alter_column('channels', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'content_type',
               existing_type=postgresql.ENUM('shorts', 'long', 'both', name='contenttype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'aspect_ratio',
               existing_type=postgresql.ENUM('9:16', '16:9', name='aspectratio'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'target_duration',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'upload_schedule',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'status',
               existing_type=postgresql.ENUM('active', 'paused', 'inactive', name='channelstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_channels_name', table_name='channels')
    op.drop_index('ix_channels_status', table_name='channels')
    op.alter_column('quality_reports', 'grammar_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'fact_consistency_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'engagement_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'retention_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'seo_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'uniqueness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'readability_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'passed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'status',
               existing_type=postgresql.ENUM('passed', 'failed', 'needs_review', name='qualitystatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quality_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_quality_reports_script_id', table_name='quality_reports')
    op.drop_constraint('quality_reports_script_id_fkey', 'quality_reports', type_='foreignkey')
    op.create_foreign_key(None, 'quality_reports', 'scripts', ['script_id'], ['id'])
    op.alter_column('research', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'complete', 'failed', name='researchstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('research', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('research', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_research_status', table_name='research')
    op.drop_index('ix_research_topic_id', table_name='research')
    op.drop_constraint('research_topic_id_fkey', 'research', type_='foreignkey')
    op.create_foreign_key(None, 'research', 'topics', ['topic_id'], ['id'])
    op.alter_column('scripts', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scripts', 'estimated_duration',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scripts', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scripts', 'status',
               existing_type=postgresql.ENUM('draft', 'approved', 'rejected', 'producing', 'complete', name='scriptstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_scripts_channel_id', table_name='scripts')
    op.drop_index('ix_scripts_script_type', table_name='scripts')
    op.drop_index('ix_scripts_status', table_name='scripts')
    op.drop_index('ix_scripts_topic_id', table_name='scripts')
    op.drop_constraint('scripts_channel_id_fkey', 'scripts', type_='foreignkey')
    op.drop_constraint('scripts_topic_id_fkey', 'scripts', type_='foreignkey')
    op.create_foreign_key(None, 'scripts', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'scripts', 'channels', ['channel_id'], ['id'])
    op.alter_column('storyboards', 'scenes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('storyboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('storyboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index('ix_storyboards_script_id', table_name='storyboards')
    op.drop_constraint('storyboards_script_id_fkey', 'storyboards', type_='foreignkey')
    op.create_foreign_key(None, 'storyboards', 'scripts', ['script_id'], ['id'])
    op.add_column('thumbnails', sa.Column('script_id', sa.UUID(), nullable=False))
    op.alter_column('thumbnails', 'status',
               existing_type=postgresql.ENUM('pending', 'generating', 'complete', 'failed', name='thumbnailstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('thumbnails', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('thumbnails', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('thumbnails_video_id_key', 'thumbnails', type_='unique')
    op.create_unique_constraint(None, 'thumbnails', ['script_id'])
    op.drop_constraint('thumbnails_video_id_fkey', 'thumbnails', type_='foreignkey')
    op.create_foreign_key(None, 'thumbnails', 'scripts', ['script_id'], ['id'])
    op.drop_column('thumbnails', 'video_id')
    op.alter_column('topics', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topics', 'source',
               existing_type=postgresql.ENUM('google_trends', 'youtube_trends', 'reddit', 'news', 'manual', 'feedback', name='topicsource'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topics', 'status',
               existing_type=postgresql.ENUM('pending', 'researching', 'scripting', 'producing', 'uploading', 'published', 'rejected', 'failed', name='topicstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topics', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('topics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_topics_channel_id', table_name='topics')
    op.drop_index('ix_topics_score', table_name='topics')
    op.drop_index('ix_topics_status', table_name='topics')
    op.drop_constraint('topics_channel_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'channels', ['channel_id'], ['id'])
    op.alter_column('uploads', 'privacy_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('uploads', 'status',
               existing_type=postgresql.ENUM('pending', 'uploading', 'published', 'failed', 'scheduled', name='uploadstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('uploads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_uploads_status', table_name='uploads')
    op.drop_index('ix_uploads_youtube_video_id', table_name='uploads')
    op.drop_constraint('uploads_video_id_fkey', 'uploads', type_='foreignkey')
    op.create_foreign_key(None, 'uploads', 'videos', ['video_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'editor', 'viewer', name='userrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.alter_column('videos', 'resolution',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('videos', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('videos', 'file_size',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('videos', 'status',
               existing_type=postgresql.ENUM('pending', 'generating', 'complete', 'failed', name='videostatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_videos_script_id', table_name='videos')
    op.drop_index('ix_videos_status', table_name='videos')
    op.drop_constraint('videos_script_id_fkey', 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'scripts', ['script_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key('videos_script_id_fkey', 'videos', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_videos_status', 'videos', ['status'], unique=False)
    op.create_index('ix_videos_script_id', 'videos', ['script_id'], unique=False)
    op.alter_column('videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('videos', 'status',
               existing_type=postgresql.ENUM('pending', 'generating', 'complete', 'failed', name='videostatus'),
               server_default=sa.text("'pending'::videostatus"),
               existing_nullable=False)
    op.alter_column('videos', 'file_size',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('videos', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('videos', 'resolution',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1920x1080'::character varying"),
               existing_nullable=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'editor', 'viewer', name='userrole'),
               server_default=sa.text("'viewer'::userrole"),
               existing_nullable=False)
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.create_foreign_key('uploads_video_id_fkey', 'uploads', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_uploads_youtube_video_id', 'uploads', ['youtube_video_id'], unique=False)
    op.create_index('ix_uploads_status', 'uploads', ['status'], unique=False)
    op.alter_column('uploads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('uploads', 'status',
               existing_type=postgresql.ENUM('pending', 'uploading', 'published', 'failed', 'scheduled', name='uploadstatus'),
               server_default=sa.text("'pending'::uploadstatus"),
               existing_nullable=False)
    op.alter_column('uploads', 'privacy_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'public'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key('topics_channel_id_fkey', 'topics', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_topics_status', 'topics', ['status'], unique=False)
    op.create_index('ix_topics_score', 'topics', ['score'], unique=False)
    op.create_index('ix_topics_channel_id', 'topics', ['channel_id'], unique=False)
    op.alter_column('topics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('topics', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'long'::character varying"),
               existing_nullable=False)
    op.alter_column('topics', 'status',
               existing_type=postgresql.ENUM('pending', 'researching', 'scripting', 'producing', 'uploading', 'published', 'rejected', 'failed', name='topicstatus'),
               server_default=sa.text("'pending'::topicstatus"),
               existing_nullable=False)
    op.alter_column('topics', 'source',
               existing_type=postgresql.ENUM('google_trends', 'youtube_trends', 'reddit', 'news', 'manual', 'feedback', name='topicsource'),
               server_default=sa.text("'google_trends'::topicsource"),
               existing_nullable=False)
    op.alter_column('topics', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.add_column('thumbnails', sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'thumbnails', type_='foreignkey')
    op.create_foreign_key('thumbnails_video_id_fkey', 'thumbnails', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'thumbnails', type_='unique')
    op.create_unique_constraint('thumbnails_video_id_key', 'thumbnails', ['video_id'])
    op.alter_column('thumbnails', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('thumbnails', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('thumbnails', 'status',
               existing_type=postgresql.ENUM('pending', 'generating', 'complete', 'failed', name='thumbnailstatus'),
               server_default=sa.text("'pending'::thumbnailstatus"),
               existing_nullable=False)
    op.drop_column('thumbnails', 'script_id')
    op.drop_constraint(None, 'storyboards', type_='foreignkey')
    op.create_foreign_key('storyboards_script_id_fkey', 'storyboards', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_storyboards_script_id', 'storyboards', ['script_id'], unique=False)
    op.alter_column('storyboards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('storyboards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('storyboards', 'scenes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.create_foreign_key('scripts_topic_id_fkey', 'scripts', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('scripts_channel_id_fkey', 'scripts', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_scripts_topic_id', 'scripts', ['topic_id'], unique=False)
    op.create_index('ix_scripts_status', 'scripts', ['status'], unique=False)
    op.create_index('ix_scripts_script_type', 'scripts', ['script_type'], unique=False)
    op.create_index('ix_scripts_channel_id', 'scripts', ['channel_id'], unique=False)
    op.alter_column('scripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('scripts', 'status',
               existing_type=postgresql.ENUM('draft', 'approved', 'rejected', 'producing', 'complete', name='scriptstatus'),
               server_default=sa.text("'draft'::scriptstatus"),
               existing_nullable=False)
    op.alter_column('scripts', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('scripts', 'estimated_duration',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('scripts', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'research', type_='foreignkey')
    op.create_foreign_key('research_topic_id_fkey', 'research', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_research_topic_id', 'research', ['topic_id'], unique=False)
    op.create_index('ix_research_status', 'research', ['status'], unique=False)
    op.alter_column('research', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('research', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('research', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'complete', 'failed', name='researchstatus'),
               server_default=sa.text("'pending'::researchstatus"),
               existing_nullable=False)
    op.drop_constraint(None, 'quality_reports', type_='foreignkey')
    op.create_foreign_key('quality_reports_script_id_fkey', 'quality_reports', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_quality_reports_script_id', 'quality_reports', ['script_id'], unique=False)
    op.alter_column('quality_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('quality_reports', 'status',
               existing_type=postgresql.ENUM('passed', 'failed', 'needs_review', name='qualitystatus'),
               server_default=sa.text("'needs_review'::qualitystatus"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'passed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('quality_reports', 'overall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'readability_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'uniqueness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'seo_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'retention_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'engagement_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'fact_consistency_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('quality_reports', 'grammar_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.create_index('ix_channels_status', 'channels', ['status'], unique=False)
    op.create_index('ix_channels_name', 'channels', ['name'], unique=False)
    op.alter_column('channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('channels', 'status',
               existing_type=postgresql.ENUM('active', 'paused', 'inactive', name='channelstatus'),
               server_default=sa.text("'active'::channelstatus"),
               existing_nullable=False)
    op.alter_column('channels', 'upload_schedule',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'daily'::character varying"),
               existing_nullable=False)
    op.alter_column('channels', 'target_duration',
               existing_type=sa.INTEGER(),
               server_default=sa.text('600'),
               existing_nullable=False)
    op.alter_column('channels', 'aspect_ratio',
               existing_type=postgresql.ENUM('9:16', '16:9', name='aspectratio'),
               server_default=sa.text("'16:9'::aspectratio"),
               existing_nullable=False)
    op.alter_column('channels', 'content_type',
               existing_type=postgresql.ENUM('shorts', 'long', 'both', name='contenttype'),
               server_default=sa.text("'both'::contenttype"),
               existing_nullable=False)
    op.alter_column('channels', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.create_foreign_key('analytics_upload_id_fkey', 'analytics', 'uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_analytics_upload_id', 'analytics', ['upload_id'], unique=False)
    op.create_index('ix_analytics_snapshot_date', 'analytics', ['snapshot_date'], unique=False)
    op.alter_column('analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('analytics', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('analytics', 'subscribers_lost',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics', 'subscribers_gained',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics', 'impressions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics', 'ctr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('analytics', 'average_view_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('analytics', 'average_view_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('analytics', 'watch_time_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('analytics', 'shares',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics', 'comments',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics', 'likes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics', 'views',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('analytics', 'snapshot_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index('ix_agent_logs_level', 'agent_logs', ['level'], unique=False)
    op.create_index('ix_agent_logs_created_at', 'agent_logs', ['created_at'], unique=False)
    op.create_index('ix_agent_logs_agent_name', 'agent_logs', ['agent_name'], unique=False)
    op.alter_column('agent_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('agent_logs', 'level',
               existing_type=postgresql.ENUM('debug', 'info', 'warning', 'error', 'critical', name='agentloglevel'),
               server_default=sa.text("'info'::agentloglevel"),
               existing_nullable=False)
    # ### end Alembic commands ###
