"""add_video_table

Revision ID: d119ce13fc55
Revises: 3292438b4131
Create Date: 2026-06-30 14:58:54.866935+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd119ce13fc55'
down_revision: Union[str, None] = '3292438b4131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Intentional no-op upgrade — this migration was mis-generated.
    # The actual video table is created by a later migration.
    # Using IF EXISTS so this is safe whether or not voices exists.
    op.execute("DROP TABLE IF EXISTS voices")
    op.execute("DROP TYPE IF EXISTS voiceprovider CASCADE")
    op.execute("DROP TYPE IF EXISTS voicestatus CASCADE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('gtts', 'pyttsx3', 'mock', 'google', 'azure', 'elevenlabs', name='voiceprovider'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'generating', 'complete', 'failed', name='voicestatus'), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('speaker', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('audio_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sample_rate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bitrate', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name='voices_script_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='voices_pkey'),
    sa.UniqueConstraint('script_id', name='voices_script_id_key')
    )
    # ### end Alembic commands ###
