"""add_voice_table

Revision ID: 3292438b4131
Revises: a245cfb48e3c
Create Date: 2026-06-29 12:18:40.680617+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3292438b4131'
down_revision: Union[str, None] = 'a245cfb48e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('gtts', 'pyttsx3', 'mock', 'google', 'azure', 'elevenlabs', name='voiceprovider'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'complete', 'failed', name='voicestatus'), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('bitrate', sa.String(length=20), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voices')
    # ### end Alembic commands ###
